Fix MOPAC citations
ltalirz/atomistic-software pull request #117
Opened 2022-04-13 03:03 UTC by godotalgorithm

This performs the changes suggested in the Issue (#114) that I opened to fix MOPAC's citation count and remove ghost Google Scholar entries from all citation counts. I am more confident making adjustments in MOPAC's case because I've already studied its history of citations in detail. Ideally, to correct other codes similarly, someone needs to start from a very permissive search string and add restrictions to remove as many false positives as possible and check that the final false positive rate isn't too large. I'd say that having code author names in the search as required elements rather than part of some OR expression is too restrictive because many codes have a substantial number of citations that mention the code without referring to the standard citation paper. It's usually not as bad as in MOPAC's case, but for example with VASP & Gaussian this would add about 30% to their citation counts by my estimate.

2022-04-13 22:40 UTC, ltalirz requested changes

2022-04-13 22:40 UTC, ltalirz commented on src/components/Columns.js
> +          searchUrl += "&hl=en&as_sdt=0%2C5&as_ylo=" + year + "&as_yhi=" + year + "&as_vis=1";
Since this change would need all citation counts to be updated, could you please remove it from this PR?

As to whether to include it in a separate PR or not, please let me know your thoughts in https://github.com/ltalirz/atomistic-software/issues/114

2022-04-13 22:40 UTC, ltalirz commented on src/data/codes.json
> +    "query_string": "MOPAC OR \"MOPAC93\" OR \"MOPAC97\" OR \"MOPAC2000\" OR \"MOPAC2007\" OR \"MOPAC2009\" OR \"MOPAC2012\" OR \"MOPAC2016\" -expressway -policing -\"Missouri Pacific\" -\"motif find
Indeed I would have never guessed that MOPAC is a street in Texas ;-) 
Thanks for contributing this carefully crafted filter

2022-04-14 02:06 UTC, godotalgorithm commented on src/components/Columns.js
> +          searchUrl += "&hl=en&as_sdt=0%2C5&as_ylo=" + year + "&as_yhi=" + year + "&as_vis=1";
As now noted in #114, this isn't problematic for atomistic.software because it doesn't consider citations before 2010. It is relevant, for example, to accurately tracking MOPAC's entire history of citations, but that's a concern of mine and not yours. This commit can be safely removed.

2022-04-14 02:18 UTC, godotalgorithm commented on src/components/Columns.js
> +          searchUrl += "&hl=en&as_sdt=0%2C5&as_ylo=" + year + "&as_yhi=" + year + "&as_vis=1";
(I removed it)

2022-04-14 08:09 UTC, ltalirz commented
Thanks, I will get to running the updates over the weekend

2022-04-14 15:19 UTC, godotalgorithm commented
What does your workflow look like for fully ingesting a new Google Scholar search string. I am still interested in improving the search strings for other codes, but I'm wondering how much of a hassle that will be for you with your current setup.

2022-04-14 15:58 UTC, ltalirz commented
> What does your workflow look like for fully ingesting a new Google Scholar search string. I am still interested in improving the search strings for other codes, but I'm wondering how much of a hassle that will be for you with your current setup.

I have some simple scripts around [scholarly](https://github.com/scholarly-python-package/scholarly), i.e. it's not hassle at all (just takes a bit of time). Further contributions are very welcome!

2022-04-15 11:13 UTC, ltalirz commented
Adding citation data in https://github.com/ltalirz/atomistic-software/pull/120

2022-04-15 11:13 UTC, closed without merging